---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Provision Instance
      amazon.aws.ec2_instance:
        name: colin-dob-ansible
        vpc_subnet_id: subnet-05e4ee8816e100972
        key_name: colin-ansible
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: True
        image_id: ami-00271c85bf8a52b84
      register: result

    - name: Add to host group
      add_host: hostname={{ item.public_ip_address }} groups=ec2hosts
      loop: "{{ result.instances }}"


- hosts: ec2hosts
  become: true
  user: ubuntu
  gather_facts: False
  tasks:
    - name: Wait for SSH connection to be established
      ansible.builtin.wait_for_connection:
        delay: 60
        sleep: 10
        timeout: 600

    - name: Install packages
      apt:
        name:
          - acl
        state: present

    - name: Ensure github-actions-runner group exists
      group:
        name: github-actions-runner
        state: present

    - name: Ensure github-actions-runner user exists
      user:
        name: github-actions-runner
        group: github-actions-runner
        home: /home/github-actions-runner
        state: present

    - name: Download the latest runner package
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.328.0/actions-runner-linux-x64-2.328.0.tar.gz
        dest: /home/github-actions-runner/actions-runner-linux-x64-2.328.0.tar.gz
        mode: "0644"
        owner: github-actions-runner
        group: github-actions-runner
        force: no
      register: pkg

    - name: Extract the installer
      unarchive:
        src: /home/github-actions-runner/actions-runner-linux-x64-2.328.0.tar.gz
        dest: /home/github-actions-runner
        remote_src: yes
      when: pkg.changed

    - name: Install runner dependencies
      command: ./bin/installdependencies.sh
      args:
        chdir: /home/github-actions-runner
      when: pkg.changed

    - name: Check if runner is already configured
      stat:
        path: /home/github-actions-runner/.runner
      register: cfg

    - name: Configure the runner
      command: ./config.sh --url https://github.com/Valinora/dob-tf --token AAIUJBGCKNFYWIGZU6JC6UTIZA6UM --unattended
      args:
        chdir: /home/github-actions-runner
        creates: /home/github-actions-runner/.runner
      become_user: github-actions-runner
      when: not cfg.stat.exists

    - name: Uninstall any existing runner service
      command: ./svc.sh uninstall
      args:
        chdir: /home/github-actions-runner
      ignore_errors: true

    - name: Install the runner service for github-actions-runner user
      command: ./svc.sh install github-actions-runner
      args:
        chdir: /home/github-actions-runner

    - name: Start the runner service
      command: ./svc.sh start
      args:
        chdir: /home/github-actions-runner
