---
- hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - acl
        state: present

    - name: Ensure github-actions-runner group exists
      group:
        name: github-actions-runner
        state: present

    - name: Ensure github-actions-runner user exists
      user:
        name: github-actions-runner
        group: github-actions-runner
        home: /home/github-actions-runner
        state: present

    - name: Download the latest runner package
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.328.0/actions-runner-linux-arm64-2.328.0.tar.gz
        dest: /home/github-actions-runner/actions-runner-linux-arm64-2.328.0.tar.gz
        mode: "0644"
        owner: github-actions-runner
        group: github-actions-runner

    - name: Extract the installer
      unarchive:
        src: /home/github-actions-runner/actions-runner-linux-arm64-2.328.0.tar.gz
        dest: /home/github-actions-runner
        remote_src: yes

    - name: Ensure runner directory ownership recursively
      file:
        path: /home/github-actions-runner
        state: directory
        owner: github-actions-runner
        group: github-actions-runner
        recurse: yes

#    - name: Configure the runner
#      command: ./config.sh --url https://github.com/n0rq1/DOB-learn-ansible --token AVLVZXA6V24P4TL6OAZMZDDIYG2LC --unattended 
#      args:
#        chdir: /home/github-actions-runner
#      become_user: github-actions-runner

    - name: Start the runner
      command: ./run.sh --unattended
      args:
        chdir: /home/github-actions-runner
      become_user: github-actions-runner