name: adfadsf

on:
  push:
    branches:
      - main

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World"